language: node_js
node_js:
  - "7"
sudo: required
services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d
  - cd integration-test
install:
  - npm install  
script:
  - npm start
after_success:
  - docker-compose down -v
after_failure:
  - docker-compose down -v